CREATE TABLE IF NOT EXISTS photo (
  id SERIAL PRIMARY KEY,
  title TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS description (
  id SERIAL PRIMARY KEY,
  photo_id INTEGER NOT NULL REFERENCES photo(id) ON DELETE CASCADE,
  text TEXT NOT NULL,
  timestamp TIMESTAMPTZ DEFAULT NOW()
);